In [ ]:
import sqlite3

# connect to the SQLite database
conn = sqlite3.connect('../data/raw/olist.sqlite')

# view the tables in the database
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = conn.execute(query).fetchall()

print("Tables:")
for table in tables:
    print(table[0])

Tables:
product_category_name_translation
sellers
customers
geolocation
order_items
order_payments
order_reviews
orders
products
leads_qualified
leads_closed

In [2]:
import pandas as pd

# query to select all records from the orders table
orders = pd.read_sql("SELECT * FROM orders LIMIT 5", conn)
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [3]:
order_items = pd.read_sql("SELECT * FROM order_items LIMIT 5", conn)
order_items

customers = pd.read_sql("SELECT * FROM customers LIMIT 5", conn)
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
order_items = pd.read_sql("SELECT * FROM order_items LIMIT 5", conn)
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [5]:
products = pd.read_sql("SELECT * FROM products LIMIT 5", conn)
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [6]:
df = pd.read_sql("SELECT * FROM sellers LIMIT 5", conn)

df.to_dict(orient="records")

[{'seller_id': '3442f8959a84dea7ee197c632cb2df15',
  'seller_zip_code_prefix': 13023,
  'seller_city': 'campinas',
  'seller_state': 'SP'},
 {'seller_id': 'd1b65fc7debc3361ea86b5f14c68d2e2',
  'seller_zip_code_prefix': 13844,
  'seller_city': 'mogi guacu',
  'seller_state': 'SP'},
 {'seller_id': 'ce3ad9de960102d0677a81f5d0bb7b2d',
  'seller_zip_code_prefix': 20031,
  'seller_city': 'rio de janeiro',
  'seller_state': 'RJ'},
 {'seller_id': 'c0f3eea2e14555b6faeea3dd58c1b1c3',
  'seller_zip_code_prefix': 4195,
  'seller_city': 'sao paulo',
  'seller_state': 'SP'},
 {'seller_id': '51a04a8a6bdcb23deccc82b0b80742cf',
  'seller_zip_code_prefix': 12914,
  'seller_city': 'braganca paulista',
  'seller_state': 'SP'}]

In [7]:
payments = pd.read_sql("SELECT * FROM order_payments LIMIT 5", conn)
payments.to_dict(orient="records")

[{'order_id': 'b81ef226f3fe1789b1e8b2acac839d17',
  'payment_sequential': 1,
  'payment_type': 'credit_card',
  'payment_installments': 8,
  'payment_value': 99.33},
 {'order_id': 'a9810da82917af2d9aefd1278f1dcfa0',
  'payment_sequential': 1,
  'payment_type': 'credit_card',
  'payment_installments': 1,
  'payment_value': 24.39},
 {'order_id': '25e8ea4e93396b6fa0d3dd708e76c1bd',
  'payment_sequential': 1,
  'payment_type': 'credit_card',
  'payment_installments': 1,
  'payment_value': 65.71},
 {'order_id': 'ba78997921bbcdc1373bb41e913ab953',
  'payment_sequential': 1,
  'payment_type': 'credit_card',
  'payment_installments': 8,
  'payment_value': 107.78},
 {'order_id': '42fdf880ba16b47b59251dd489d4441a',
  'payment_sequential': 1,
  'payment_type': 'credit_card',
  'payment_installments': 2,
  'payment_value': 128.45}]

In [8]:
reviews = pd.read_sql("SELECT * FROM order_reviews LIMIT 5", conn)
reviews.to_dict(orient="records")

[{'review_id': '7bc2406110b926393aa56f80a40eba40',
  'order_id': '73fc7af87114b39712e6da79b0a377eb',
  'review_score': 4,
  'review_comment_title': None,
  'review_comment_message': nan,
  'review_creation_date': '2018-01-18 00:00:00',
  'review_answer_timestamp': '2018-01-18 21:46:59'},
 {'review_id': '80e641a11e56f04c1ad469d5645fdfde',
  'order_id': 'a548910a1c6147796b98fdf73dbeba33',
  'review_score': 5,
  'review_comment_title': None,
  'review_comment_message': nan,
  'review_creation_date': '2018-03-10 00:00:00',
  'review_answer_timestamp': '2018-03-11 03:05:13'},
 {'review_id': '228ce5500dc1d8e020d8d1322874b6f0',
  'order_id': 'f9e4b658b201a9f2ecdecbb34bed034b',
  'review_score': 5,
  'review_comment_title': None,
  'review_comment_message': nan,
  'review_creation_date': '2018-02-17 00:00:00',
  'review_answer_timestamp': '2018-02-18 14:36:24'},
 {'review_id': 'e64fb393e7b32834bb789ff8bb30750e',
  'order_id': '658677c97b385a9be170737859d3511b',
  'review_score': 5,
  'review_comment_title': None,
  'review_comment_message': 'Recebi bem antes do prazo estipulado.',
  'review_creation_date': '2017-04-21 00:00:00',
  'review_answer_timestamp': '2017-04-21 22:02:06'},
 {'review_id': 'f7c4243c7fe1938f181bec41a392bdeb',
  'order_id': '8e6bfb81e283fa7e4f11123a3fb894f1',
  'review_score': 5,
  'review_comment_title': None,
  'review_comment_message': 'Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa',
  'review_creation_date': '2018-03-01 00:00:00',
  'review_answer_timestamp': '2018-03-02 10:26:53'}]